### ISSUE TITLE
以后会不会考虑考虑 github lfs

### ISSUE THREAD

**Issue by Alafun** [TenMoons/AHU-CS-Repository#5]

**Comment by TenMoons** [comment]
大概了解了一下LFS免费容量是1GB，可能不够使用，学期结束之后会把仓库资料整理精简一下，再看有无好的解决方案。

**Comment by Alafun** [comment]
lfs 有费用吗，我还没太了解这个相关的收费方面。lfs听说有个好处就是版本更新 可以不用全量更新 😄

**Comment by Alafun** [comment]
![image](https://user-images.githubusercontent.com/78416589/147777698-43efe171-4ca6-4733-add9-9e84f4105178.png)

**Comment by TenMoons** [comment]
你好，邮件我已收到。
