### ISSUE TITLE
为什么这个 readme 变成这个了

### ISSUE THREAD

**Issue by Alafun** [TenMoons/AHU-CS-Repository#9]
![image](https://user-images.githubusercontent.com/78416589/147730703-c234d263-3a6c-4f6e-9fc3-37977d80df7a.png)
![image](https://user-images.githubusercontent.com/78416589/147730703-c234d263-3a6c-4f6e-9fc3-37977d80df7a.png)
好神奇呀，明明有当前路径下有 `README.md` 怎么不解析呀

**Comment by Alafun** [comment]
https://github.com/TenMoons/AHU-CS-Repository/pull/8#issue-1090835613

**Comment by Alafun** [comment]
> [#8 (comment)](https://github.com/TenMoons/AHU-CS-Repository/pull/8#issue-1090835613)

在[官方文档](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes)查了是因为下面这个吗？
![image](https://user-images.githubusercontent.com/78416589/147731471-ad7c4f9a-c32b-47a2-a3c0-b79a0be72c69.png)

**Comment by TenMoons** [comment]
咱也不懂...
